permalink: /:categories/:title.html
safe: false
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
paginate: 10
encoding: utf-8
markdown: kramdown


title: Suemi Blog
tagline: 人生五十年
# 作者信息
author: 
  name: suemi
  email: suemi94@163.com
  link: http://segmentfault.com/u/suemi
  weibo: http://weibo.com/u/2186120180
  github: http://github.com/suemi994
  academic: http://suemi.info


# 站点信息

#url: http://suemi994.github.io
rss_url: /pages/atom.xml

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : /assets/themes/twitter
  IMAGE_PATH : false
  archive_path: /pages/archive.html
  categories_path : /pages/categories.html
  tags_path : /pages/tags.html
  atom_path : /pages/atom.xml
  rss_path : /pages/rss.xml
  messages_path : /pages/messages.html
  about_path : /pages/about.html
  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments:
    provider: disqus
    duoshuo:
      short_name: suemi
    disqus:
      shortname: suemi

  analytics :
    provider : google
    google : 
      tracking_id : 'UA-58628423-1'

  sharing:
    provider: bshare
    bshare:
      shortname: suemi

#Jiathis分享插件设置
jiathis: 2002913

#google analytics 设置



# disqus 设置






